<?php



namespace P4\BookingBundle\Repository;


/**
 * ScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.²
 */
class ScheduleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDate($date)
    {
        $qb = $this->createQueryBuilder('p')//prendre première ligne
                ->select('p')
                ->where('p.date = :date')
                ->setParameter(':date',$date);
        
        return $qb->getQuery()
                ->getOneOrNullResult();
    }
    
    public function update($scheduled, $count, $date)
    {
       $em = $this->_em;
       
       if(is_null($scheduled))
       {
           $schedule = new \P4\BookingBundle\Entity\Schedule();  
           $schedule->setDate($date);
           $schedule->setCount($count);
           $em->persist($schedule);
           $em->flush();
       }
       else 
       {
        $oldcount = $scheduled->getCount();
        $scheduled->setCount($oldcount + $count);
        $scheduled = $em->merge($scheduled);
        $em->flush();
       }
       
       
    }
}
