<?php


namespace P4\BookingBundle\Repository;


/**
 * ScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBy($date)
    {
        $qb = $this->_em->createQueryBuilder()
                ->select('a')
                ->from('schedule')
                ->where('a.date = :date');
        
        return $qb->getQuery()
                ->getResult();
    }
}
